pipeline {
    agent any
    tools {nodejs "nodejs"}
    
    stages {
      
      stage("Newman package installation") {
        steps {
          sh 'npm install -g newman'
        }
      }
      stage("Run newman") {
        steps {
          sh 'newman run Webinaire/Webinaire.postman_collection.json -e Webinaire/ProdWebinaire.postman_environment.json '
        }
      }
    }
}